<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZJdWvSi\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZJdWvSi/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZJdWvSi.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZJdWvSi\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerZJdWvSi\App_KernelProdContainer([
    'container.build_hash' => 'ZJdWvSi',
    'container.build_id' => '0588b7e5',
    'container.build_time' => 1651086469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZJdWvSi');
