<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin_add' => [['id'], ['_controller' => 'App\\Controller\\AdminController::add'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/ajout']], [], [], []],
    'admin_users' => [[], ['_controller' => 'App\\Controller\\AdminController::usersList'], [], [['text', '/admin/utilisateurs']], [], [], []],
    'admin_edit_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editUser'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/utilisateur/modifier']], [], [], []],
    'admin_delete_user' => [['id'], ['_controller' => 'App\\Controller\\AdminController::deleteUser'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/admin/utilisateur/supprimer']], [], [], []],
    'admin_add_product' => [[], ['_controller' => 'App\\Controller\\AdminController::addProduct'], [], [['text', '/admin/produit/ajouter']], [], [], []],
    'produit_products' => [[], ['_controller' => 'App\\Controller\\ProduitController::productList'], [], [['text', '/produit/listeproduits']], [], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/security/inscription']], [], [], []],
    'security_app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/security/login']], [], [], []],
    'security_app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/security/logout']], [], [], []],
    'site' => [[], ['_controller' => 'App\\Controller\\SiteController::index'], [], [['text', '/']], [], [], []],
    'add' => [['id'], ['_controller' => 'App\\Controller\\SiteController::add'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/ajout']], [], [], []],
    'del' => [['id'], ['_controller' => 'App\\Controller\\SiteController::del'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/supprimer']], [], [], []],
    'super_admin_listadmins' => [[], ['_controller' => 'App\\Controller\\SuperAdminController::usersList'], [], [['text', '/sadmin/listadmins']], [], [], []],
    'user_edit' => [['id'], ['_controller' => 'App\\Controller\\UserController::editUser'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/user/utilisateur/modifier']], [], [], []],
    'user_edit2' => [['id'], ['_controller' => 'App\\Controller\\UserController::editUser2'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/user/utilisateur2/modifier']], [], [], []],
    'user_panier' => [['id'], ['_controller' => 'App\\Controller\\UserController::panierUser'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/user/utilisateur/panier']], [], [], []],
    'user_delete_product' => [['id'], ['_controller' => 'App\\Controller\\UserController::deleteProduct'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/user/user/supprimer']], [], [], []],
];
