<?php

namespace ContainerWFqxG40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Sandbox\\SandboxDoctrineController::ajouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::effacerendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::modifierendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::viewAction' => ['privates', '.service_locator.PHfHe2Z', 'get_ServiceLocator_PHfHe2ZService', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController::createFlashAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController::deuxAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:ajouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:effacerendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:modifierendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:viewAction' => ['privates', '.service_locator.PHfHe2Z', 'get_ServiceLocator_PHfHe2ZService', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController:createFlashAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController:deuxAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Sandbox\\SandboxDoctrineController::ajouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::effacerendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::modifierendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::viewAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController::createFlashAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController::deuxAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:ajouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:effacerendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:modifierendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:viewAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController:createFlashAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController:deuxAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
