<?php

namespace ContainerWFqxG40;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilmRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\FilmRepository' shared autowired service.
     *
     * @return \App\Repository\FilmRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\FilmRepository'] = new \App\Repository\FilmRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
