<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD7y1Flb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD7y1Flb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD7y1Flb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD7y1Flb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD7y1Flb\App_KernelDevDebugContainer([
    'container.build_hash' => 'D7y1Flb',
    'container.build_id' => '0f1ad494',
    'container.build_time' => 1651096050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD7y1Flb');
