<?php

namespace ContainerD7y1Flb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTotalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Total' shared autowired service.
     *
     * @return \App\Service\Total
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Total.php';

        return $container->privates['App\\Service\\Total'] = new \App\Service\Total();
    }
}
