<?php

namespace Container66sxltw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DiKAas2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.diKAas2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.diKAas2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Sandbox\\SandboxDoctrineController::ajouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueAjouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueView1Action' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueView2Action' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::deleteAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::effacerendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::modifierendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController::viewAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController::filmEditAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController::filmEditBisAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController::filmValidationAction' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController::createFlashAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController::deuxAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxProduitController::deleteAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxProduitController::listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxProduitController::viewAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:ajouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueAjouterendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueView1Action' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueView2Action' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:deleteAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:effacerendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:modifierendurAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxDoctrineController:viewAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController:filmEditAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController:filmEditBisAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\Sandbox\\SandboxFormController:filmValidationAction' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController:createFlashAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxInjectionController:deuxAction' => ['privates', '.service_locator.LQ80LD8', 'get_ServiceLocator_LQ80LD8Service', true],
            'App\\Controller\\Sandbox\\SandboxProduitController:deleteAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxProduitController:listAction' => ['privates', '.service_locator.T7xmfzk', 'get_ServiceLocator_T7xmfzkService', true],
            'App\\Controller\\Sandbox\\SandboxProduitController:viewAction' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\Sandbox\\SandboxDoctrineController::ajouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueAjouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueView1Action' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::critiqueView2Action' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::deleteAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::effacerendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::modifierendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController::viewAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController::filmEditAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController::filmEditBisAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController::filmValidationAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController::createFlashAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController::deuxAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController::deleteAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController::listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController::viewAction' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:ajouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueAjouterendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueView1Action' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:critiqueView2Action' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:deleteAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:effacerendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:modifierendurAction' => '?',
            'App\\Controller\\Sandbox\\SandboxDoctrineController:viewAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController:filmEditAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController:filmEditBisAction' => '?',
            'App\\Controller\\Sandbox\\SandboxFormController:filmValidationAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController:createFlashAction' => '?',
            'App\\Controller\\Sandbox\\SandboxInjectionController:deuxAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController:deleteAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController:listAction' => '?',
            'App\\Controller\\Sandbox\\SandboxProduitController:viewAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
